version: '3.8'

services:
  app:
    image: php:8.1-apache
    ports:
      - "8000:80"
    volumes:
      - ./.env:/var/www/.env
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: api
      DB_USERNAME: root
      DB_PASSWORD: password
    depends_on:
      - database

  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: api
